# --- UPDATED VERSION WITH ENHANCED ERROR HANDLING ---
import vertexai  # Keep if needed for other parts, but not used here
from google import genai
from google.genai.types import Part, GenerateContentConfig, HarmCategory, HarmBlockThreshold
from google.cloud import speech
import json
import os

# Ensure environment variables are set
if not os.getenv("GOOGLE_CLOUD_PROJECT"):
    raise ValueError("GOOGLE_CLOUD_PROJECT environment variable not set. Please set it to 'kalakriti-ai'.")

def transcribe_audio(audio_content: bytes) -> str:
    try:
        client = speech.SpeechClient()
        audio = speech.RecognitionAudio(content=audio_content)
        config = speech.RecognitionConfig(
            encoding=speech.RecognitionConfig.AudioEncoding.MP3,
            sample_rate_hertz=16000,
            language_code="pa-IN"
        )
        response = client.recognize(config=config, audio=audio)
        if response.results and response.results[0].alternatives:
            return response.results[0].alternatives[0].transcript
        else:
            return json.dumps({"error": "Could not transcribe audio from the provided file."})
    except Exception as e:
        print(f"DEBUG: Error in transcription: {e}")
        return json.dumps({"error": f"Error during audio transcription. Check file format (MP3) and language (pa-IN)."})

def generate_text_for_art(image_content: bytes, audio_content: bytes) -> str:
    artisan_story_transcript = transcribe_audio(audio_content)

    try:
        transcript_data = json.loads(artisan_story_transcript)
        if "error" in transcript_data:
            return json.dumps({"error": f"Transcription failed: {transcript_data['error']}"})
    except (json.JSONDecodeError, TypeError):
        pass  # Proceed if transcription is valid text

    try:
        client = genai.Client(project="kalakriti-ai", location="us-central1")
    except Exception as e:
        print(f"DEBUG: Error initializing Gen AI client: {e}")
        return json.dumps({"error": "Failed to initialize AI client. Check authentication and project settings."})

    if not image_content or not audio_content:
        return json.dumps({"error": "Missing image or audio file in request."})

    image_part = Part.from_bytes(data=image_content, mime_type="image/jpeg")

    text_prompt = f"""
    You are an expert brand strategist and copywriter specializing in empowering local artisans. 
    Your task is to create a complete, professional, and emotionally resonant marketing kit based on the provided image of a handcrafted product and the artisan's own story.

    **Artisan's Story:**
    "{artisan_story_transcript}"

    **Your Instructions:**
    Respond ONLY with a valid JSON object with the following structure, without any additional formatting (e.g., no ```json
    {{
      "productTitle": "A concise, SEO-friendly title.",
      "productDescription": "A detailed, poetic description for an e-commerce website.",
      "socialMediaCaption": "An engaging caption for Instagram with emojis and hashtags.",
      "artisanStory": "A short, narrative paragraph about the artisan's craft."
    }}
    """

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[image_part, text_prompt],
            config=GenerateContentConfig(
                safety_settings=[
                    {
                        "category": HarmCategory.HARM_CATEGORY_HARASSMENT,
                        "threshold": HarmBlockThreshold.BLOCK_ONLY_HIGH
                    },
                    {
                        "category": HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                        "threshold": HarmBlockThreshold.BLOCK_ONLY_HIGH
                    }
                ]
            )
        )
        if not response.text or not response.text.strip():
            print(f"DEBUG: Empty response from Gemini: {response}")
            return json.dumps({"error": "No content generated by AI model."})
        return response.text
    except Exception as e:
        print(f"DEBUG: Error generating content from Gemini: {e}")
        return json.dumps({"error": "Failed to generate content from AI model. Check logs for details."})