# --- FINAL OPTIMIZED PROMPT FOR ACCESSIBLE LANGUAGE AND SHORT DESCRIPTION ---
import vertexai
from google import genai
from google.genai.types import Part, GenerateContentConfig, HarmCategory, HarmBlockThreshold
from google.cloud import speech
import json
import os

# Ensure environment variables are set
if not os.getenv("GOOGLE_CLOUD_PROJECT"):
    pass 

def transcribe_audio(audio_content: bytes) -> str:
    try:
        client = speech.SpeechClient()
        audio = speech.RecognitionAudio(content=audio_content)
        config = speech.RecognitionConfig(
            encoding=speech.RecognitionConfig.AudioEncoding.MP3,
            sample_rate_hertz=16000,
            language_code="pa-IN"
        )
        response = client.recognize(config=config, audio=audio)
        if response.results and response.results[0].alternatives:
            return response.results[0].alternatives[0].transcript
        else:
            return json.dumps({"error": "Could not transcribe audio from the provided file."})
    except Exception as e:
        print(f"DEBUG: Error in transcription: {e}")
        return json.dumps({"error": f"Error during audio transcription. Check file format (MP3) and language (pa-IN)."})

def generate_text_for_art(image_content: bytes, audio_content: bytes) -> str:
    artisan_story_transcript = transcribe_audio(audio_content)

    try:
        transcript_data = json.loads(artisan_story_transcript)
        if "error" in transcript_data:
            return json.dumps({"error": f"Transcription failed: {transcript_data['error']}"})
    except (json.JSONDecodeError, TypeError):
        pass

    try:
        client = genai.Client()
    except Exception as e:
        print(f"DEBUG: Error initializing Gen AI client: {e}")
        return json.dumps({"error": "Failed to initialize AI client. Check authentication and project settings."})

    if not image_content:
        return json.dumps({"error": "Missing image file in request."})

    image_part = Part.from_bytes(data=image_content, mime_type="image/jpeg")

    # --- FINAL REFINED PROMPT FOR SIMPLE LANGUAGE, SHORT DESCRIPTION, AND MAX VISIBILITY ---
    # --- [NEW SIMPLIFIED AND CORRECTED PROMPT] ---
    text_prompt = f"""
    You are an expert social media strategist for artisanal crafts. Your goal is to create a marketing kit from the attached product image and the artisan's story.

    **Artisan's Story Transcript:**
    "{artisan_story_transcript}"

    **Crucial Instructions:**
    1.  **Language:** Use simple, easy-to-understand language.
    2.  **Conciseness:** Keep all descriptions short and persuasive.
    3.  **JSON Structure:** Respond ONLY with a valid JSON object using the exact keys specified below. Do not add ```json markdown.

    **Your Response JSON Structure:**
    {{
      "productTitle": "A concise, SEO-friendly title (5-8 words).",
      "productDescription": "A persuasive product description for a sales page (3-4 sentences max).",
      "mainPostDescription": "An engaging social media caption for the main post body, can include emojis (2-3 sentences).",
      "hashtags": "A single string containing 10-15 relevant and trending hashtags, starting with #.",
      "artisanStory": "A short, narrative paragraph about the artisan's craft based on their story."
    }}
    """

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[image_part, text_prompt],
            config=GenerateContentConfig(
                safety_settings=[
                    {
                        "category": HarmCategory.HARM_CATEGORY_HARASSMENT,
                        "threshold": HarmBlockThreshold.BLOCK_ONLY_HIGH
                    },
                    {
                        "category": HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                        "threshold": HarmBlockThreshold.BLOCK_ONLY_HIGH
                    }
                ]
            )
        )
        if not response.text or not response.text.strip():
            print(f"DEBUG: Empty response from Gemini: {response}")
            return json.dumps({"error": "No content generated by AI model."})
        return response.text
    except Exception as e:
        print(f"DEBUG: Error generating content from Gemini: {e}")
        return json.dumps({"error": "Failed to generate content from AI model. Check logs for details."})