# --- FINAL OPTIMIZED PROMPT FOR ACCESSIBLE LANGUAGE AND SHORT DESCRIPTION ---
import vertexai
from google import genai
from google.genai.types import Part, GenerateContentConfig, HarmCategory, HarmBlockThreshold
from google.cloud import speech
import json
import os

# Ensure environment variables are set
if not os.getenv("GOOGLE_CLOUD_PROJECT"):
    pass 

def transcribe_audio(audio_content: bytes) -> str:
    try:
        client = speech.SpeechClient()
        audio = speech.RecognitionAudio(content=audio_content)
        config = speech.RecognitionConfig(
            encoding=speech.RecognitionConfig.AudioEncoding.MP3,
            sample_rate_hertz=16000,
            language_code="pa-IN"
        )
        response = client.recognize(config=config, audio=audio)
        if response.results and response.results[0].alternatives:
            return response.results[0].alternatives[0].transcript
        else:
            return json.dumps({"error": "Could not transcribe audio from the provided file."})
    except Exception as e:
        print(f"DEBUG: Error in transcription: {e}")
        return json.dumps({"error": f"Error during audio transcription. Check file format (MP3) and language (pa-IN)."})

def generate_text_for_art(image_content: bytes, audio_content: bytes) -> str:
    artisan_story_transcript = transcribe_audio(audio_content)

    try:
        transcript_data = json.loads(artisan_story_transcript)
        if "error" in transcript_data:
            return json.dumps({"error": f"Transcription failed: {transcript_data['error']}"})
    except (json.JSONDecodeError, TypeError):
        pass

    try:
        client = genai.Client()
    except Exception as e:
        print(f"DEBUG: Error initializing Gen AI client: {e}")
        return json.dumps({"error": "Failed to initialize AI client. Check authentication and project settings."})

    if not image_content:
        return json.dumps({"error": "Missing image file in request."})

    image_part = Part.from_bytes(data=image_content, mime_type="image/jpeg")

    # --- FINAL REFINED PROMPT FOR SIMPLE LANGUAGE, SHORT DESCRIPTION, AND MAX VISIBILITY ---
    text_prompt = f"""
    You are an expert social media strategist and copywriter for artisanal crafts. 
    Your goal is to create a complete marketing kit from the attached image of a product and the artisan's story.
    
    **Artisan's Story Transcript:**
    "{artisan_story_transcript}"

    **Crucial Instructions:**
    1. **Product Description:** The description MUST be concise (max 3-4 sentences), highly persuasive, and written in **simple words, and easy-to-understand language** (avoid complex or flowery vocabulary). Focus on customer benefits and emotional connection for a direct sales page.
    2. **Social Media Caption (Hashtags):** This field MUST contain ONLY a continuous string of 10 to 15 highly effective, trending, and relevant hashtags. These hashtags must be optimized for maximum reach and target buyers interested in culture, craft, and aesthetics to ensure the startup's growth. NO descriptive text or emojis.
    3. **Content Swap:** The content for the primary post description should be placed in the "postHashtags" field.

    **Your Response:**
    Respond ONLY with a valid JSON object with the following structure, without any additional formatting (e.g., no ```json):
    {{
      "productTitle": "A concise, SEO-friendly title (5-8 words).",
      "productDescription": "A concise, persuasive description (3-4 sentences maximum) using simple language.",
      "socialMediaCaption": "#HighImpactHashtag1 #HighImpactHashtag2 #HighImpactHashtag3 #... (10 to 15 total)",
      "postHashtags": "An engaging, short description (2-3 sentences) suitable for the main post body, including emojis.",
      "artisanStory": "A short, narrative paragraph about the artisan's craft."
    }}
    """

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[image_part, text_prompt],
            config=GenerateContentConfig(
                safety_settings=[
                    {
                        "category": HarmCategory.HARM_CATEGORY_HARASSMENT,
                        "threshold": HarmBlockThreshold.BLOCK_ONLY_HIGH
                    },
                    {
                        "category": HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                        "threshold": HarmBlockThreshold.BLOCK_ONLY_HIGH
                    }
                ]
            )
        )
        if not response.text or not response.text.strip():
            print(f"DEBUG: Empty response from Gemini: {response}")
            return json.dumps({"error": "No content generated by AI model."})
        return response.text
    except Exception as e:
        print(f"DEBUG: Error generating content from Gemini: {e}")
        return json.dumps({"error": "Failed to generate content from AI model. Check logs for details."})