runtime: python311

handlers:
# This handler serves the API endpoints.
- url: /api/.*
  script: auto

# This handler serves the static files (css, js, images) of our React app.
- url: /static
  static_dir: static/static

# This handler serves the main index.html file for all other routes.
- url: /.*
  static_files: static/index.html
  upload: static/index.html