runtime: python311

# This entrypoint is crucial for App Engine to start your Flask app using Gunicorn.
entrypoint: gunicorn -b :$PORT main:app

handlers:
# This handler routes all requests to your Flask application.
- url: /.*
  script: auto