# --- RUN COMMMAND: functions-framework --target=api
import os
import json
import re
from io import BytesIO
import functions_framework
from flask import jsonify, send_file, request

# Load environment variables FIRST
from dotenv import load_dotenv
load_dotenv()
GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID", "kalakriti-ai")
GCP_REGION = os.getenv("GCP_REGION", "us-central1")
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT", GCP_PROJECT_ID)
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "service-account-key.json")

import vertexai
from services import marketing_copilot, brand_studio, audio_story

# Initialize Vertex AI with fallback
try:
    vertexai.init(project=GCP_PROJECT_ID, location=GCP_REGION)
    print(f"DEBUG: Vertex AI initialized for project {GCP_PROJECT_ID} in {GCP_REGION}")
except Exception as e:
    print(f"DEBUG: Failed to initialize Vertex AI: {e}")
    raise

@functions_framework.http
def api(request):
    print(f"DEBUG: Received request for path: '{request.path}' with method: {request.method}")

    # Set a base set of CORS headers to be used for all responses
    headers = {
        'Access-Control-Allow-Origin': 'http://localhost:3000',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Max-Age': '3600'
    }

    # Handle the preflight OPTIONS request
    if request.method == 'OPTIONS':
        return ('', 204, headers)

    # All other routes will now return with these headers as well
    if request.path == '/' and request.method == 'GET':
        return jsonify({"status": "KalaKriti AI Backend is running!"}), 200, headers

    elif request.path == '/generate-marketing-kit' and request.method == 'POST':
        if 'image' not in request.files or 'audio' not in request.files:
            return jsonify({"error": "Missing image or audio file."}), 400, headers

        image_content = request.files['image'].read()
        audio_content = request.files['audio'].read()

        try:
            generated_kit_str = marketing_copilot.generate_text_for_art(image_content, audio_content)
            print(f"DEBUG: Raw response from generate_text_for_art: {generated_kit_str}")
            if not generated_kit_str or not generated_kit_str.strip():
                return jsonify({"error": "No content generated by AI model."}), 500, headers
            
            cleaned_str = re.sub(r'^```json\n|\n```$', '', generated_kit_str, flags=re.MULTILINE).strip()
            generated_kit_json = json.loads(cleaned_str)
            return jsonify(generated_kit_json), 200, headers
        except json.JSONDecodeError as e:
            print(f"DEBUG: JSON decode error: {e} - Raw response length: {len(generated_kit_str)} - Content: {repr(generated_kit_str)}")
            return jsonify({"error": f"Invalid JSON response from AI: {e}"}), 500, headers
        except Exception as e:
            print(f"DEBUG: Internal error: {e}")
            return jsonify({"error": f"Internal server error: {e}"}), 500, headers

    elif request.path == '/generate-brand-kit' and request.method == 'POST':
        if 'images' not in request.files:
            return jsonify({"error": "No image files found."}), 400, headers
        image_files = request.files.getlist('images')
        if not image_files or image_files[0].filename == '':
            return jsonify({"error": "No selected image files."}), 400, headers
        image_contents = [file.read() for file in image_files]
        try:
            generated_kit_str = brand_studio.generate_brand_kit(image_contents)
            if not generated_kit_str or not generated_kit_str.strip():
                return jsonify({"error": "No content generated by AI model."}), 500, headers
            generated_kit_json = json.loads(generated_kit_str)
            return jsonify(generated_kit_json), 200, headers
        except json.JSONDecodeError as e:
            print(f"DEBUG: JSON decode error: {e} - Raw response: {generated_kit_str}")
            return jsonify({"error": f"Invalid JSON response from AI: {e}"}), 500, headers
        except Exception as e:
            print(f"DEBUG: Internal error: {e}")
            return jsonify({"error": f"Internal server error: {e}"}), 500, headers

    elif request.path == '/generate-audio-story' and request.method == 'POST':
        if 'audio' not in request.files:
            return jsonify({"error": "Missing audio file."}), 400, headers
        audio_content = request.files['audio'].read()
        try:
            final_audio_bytes = audio_story.create_audio_story(audio_content)
            if final_audio_bytes:
                return send_file(
                    BytesIO(final_audio_bytes),
                    mimetype='audio/mpeg',
                    as_attachment=True,
                    download_name='kalakriti_story.mp3'
                ), 200, headers
            else:
                return jsonify({"error": "Failed to create audio story."}), 500, headers
        except Exception as e:
            print(f"DEBUG: Internal error: {e}")
            return jsonify({"error": f"Internal server error: {e}"}), 500, headers
    else:
        return jsonify({"error": f"Not Found: {request.path}"}), 404, headers
